<?php

declare(strict_types=1);

use Bold\CheckoutPaymentBooster\ViewModel\Hyva\Bold;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** Bold Checkout SPI template for Hyva theme. */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var Bold $viewModel */
$viewModel = $block->getViewModel();
?>
<div id="bold_fastlane"></div>

<!-- Load and initialize payments_sdk -->
<script type='module'>
    const storeBoldConfiguration = () => {
        console.log('storeFastlaneBoldConfiguration');
        Alpine.store('bold', <?= /* @noEscape */ $viewModel->getBoldConfigJson() ?>);
    };
    const loadFastlaneSDK = async () => {
        if (window.boldFastlaneInstance) {
            return;
        }
        console.log('loadFastlaneSDK');
    };
    const renderFastlane = async () => {
        if (!window.boldFastlaneInstance) {
            return;
        }
        console.log('renderFastlane');
    };
    const init = async () => {
        if (typeof Alpine !== 'undefined') {
            await storeBoldConfiguration();
            await loadFastlaneSDK();
            await renderFastlane();
            return;
        }
        document.addEventListener('alpine:init', async () => {
            await storeBoldConfiguration();
            await loadFastlaneSDK();
            await renderFastlane();
        });
    };
    init();
</script>
